### ISSUE TITLE
Problem with too many parameters on large GraphQL description files

### ISSUE THREAD

**Issue by xtroce** [kobylynskyi/graphql-java-codegen#1147] opened 2023-04-03 08:02 UTC
## Issue Description

With a big graphqls file (i try to generate the API from shopify) i get the problem that constructors are created that do not compile.  (I attached a file to reproduce it, just rename it from txt to graphqls)

[2022-10.txt](https://github.com/kobylynskyi/graphql-java-codegen/files/11136072/2022-10.txt)

## Steps to Reproduce

take a large file with more that 255 parameters going into MutationClientModel
generate code
compile

## Expected Result

it should either split up the result-file or use a builder or injection of some kind

## Actual Result

the compilation fails with error:

/graphql/client/model/MutationClientModel.java:[357,12] too many parameters

## Your Environment and Setup

* **graphql-java-codegen version**: 5.7.1
* **Build tool**: Maven
* **Mapping Config**: 

```xml

                            <configuration>
                                <graphqlSchemaPaths>
                                    <graphqlSchemaPath>${project.basedir}/src/main/resources/2022-10.graphqls
                                    </graphqlSchemaPath>
                                </graphqlSchemaPaths>
                                <outputDir>${project.basedir}/src/gen/java</outputDir>
                                <apiPackageName>graphql.client.api</apiPackageName>
                                <modelPackageName>graphql.client.model
                                </modelPackageName>
                                <customTypesMapping>
                                    <Date>java.util.Date</Date>
                                    <DateTime>java.util.Date</DateTime>
                                    <Decimal>java.math.BigDecimal</Decimal>
                                    <FormattedString>java.lang.String</FormattedString>
                                    <HTML>java.lang.String</HTML>
                                    <JSON>org.json.JSONObject</JSON>
                                    <Money>java.math.BigDecimal</Money>
                                    <StorefrontID>java.lang.String</StorefrontID>
                                    <UnsignedInt64>java.lang.Long</UnsignedInt64>
                                    <URL>java.lang.String</URL>
                                    <UtcOffset>java.lang.String</UtcOffset>
                                </customTypesMapping>
                                <modelNameSuffix>ClientModel</modelNameSuffix>
                                <requestSuffix>ClientRequest</requestSuffix>
                                <responseProjectionSuffix>ClientResponseProjection</responseProjectionSuffix>
                                <parametrizedInputSuffix>ClientParametrizedInput</parametrizedInputSuffix>
                                <typeResolverSuffix>TypeResolver</typeResolverSuffix>
                                <generateClient>true</generateClient>
                                <generateApis>true</generateApis>
                                <generateModelsForRootTypes>true</generateModelsForRootTypes>
                                <generateParameterizedFieldsResolvers>false</generateParameterizedFieldsResolvers>
                            </configuration>
```

**Comment by kobylynskyi** [comment] 2023-04-03 11:33
Duplicate of #1017.
Set `generateNoArgsConstructorOnly=true`

**Closed** 2023-04-03 11:33 UTC
Labels: bug
