### ISSUE TITLE
it will conflict when custom model named the same as java.lang.*

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#229] opened 2020-07-16 10:03 UTC
## Issue Description

1. I want to know how to use custom scalar parsing when parsing JSON without using spring IOC
2. i use graphql interface hava failed:   
```
Cannot construct instance of `io.github.dreamylost.model.Character` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (PushbackInputStream); line: 1, column: 17] (through reference chain: io.github.dreamylost.model.HeroQueryResponse["data"]->java.util.LinkedHashMap["hero"])
```

i use java main method, instance of spring bean，so i create a RestTemplate with new to execute request
this is my client example:
```
    @Override
    public Character hero(Episode episode) throws Exception {
        HeroQueryRequest heroQueryRequest = new HeroQueryRequest();
        heroQueryRequest.setEpisode(episode);

        CharacterResponseProjection characterResponseProjection = new CharacterResponseProjection();
        characterResponseProjection.id().name().onDroid(new DroidResponseProjection().id().name());

        GraphQLRequest graphQLRequest = new GraphQLRequest(heroQueryRequest, characterResponseProjection);
       //will error， I'm not familiar with this, so i create a issue
        HeroQueryResponse result = Config.restTemplate.exchange(URI.create(Config.productUrl), HttpMethod.POST, Config.httpEntity(graphQLRequest), HeroQueryResponse.class).getBody();

        assert result != null;
        return result.hero();

    }
```

## Steps to Reproduce
*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result
*Explain in detail what behavior you expected to happen.*

## Actual Result
*Explain in detail what behavior actually happened.*

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 2.2.1*
* **Build tool**: *E.g.: SBT*
* **Java tool**: *E.g.: Java 8u241*
* **Mapping Config**: *E.g.:* 

```
import java.util

name := "sbt-codegen-exmaple"

version := "1.0.0-SNAPSHOT"

organization := "io.github.dreamylost"


enablePlugins(GraphQLCodegenPlugin)

libraryDependencies ++= GraphQLCodegen ++ Seq(
  "org.springframework" % "spring-web" % "5.2.7.RELEASE"
) ++  Seq(
  "org.apache.logging.log4j" %% "log4j-api-scala" % "11.0",
  "org.apache.logging.log4j" % "log4j-api" % "2.8.2",
  "org.apache.logging.log4j" % "log4j-core" % "2.8.2",
  "org.apache.logging.log4j" % "log4j-slf4j-impl" % "2.8.2")


graphqlSchemaPaths := Array("src/main/resources/schema.graphqls")
modelPackageName := Some("io.github.dreamylost.model")
apiPackageName := Some("io.github.dreamylost.api")
generateClient := Some(true)
generateApis := Some(true)
customTypesMapping := {
  val mapping = new util.HashMap[String, String]
  mapping.put("Email", "io.github.dreamylost.scalar.EmailScalar")
  mapping
}
```

## Additional context

this is draft impl and example for sbt : https://github.com/jxnu-liguobin/graphql-java-codegen/tree/master/plugins/sbt/graphql-java-codegen-sbt-plugin , but i don't know about GraphQLCodegenConfiguration and if i  impl GraphQLCodegenConfiguration, can not use settingKey in override method in sbt, so i do not impl it.

**Comment by kobylynskyi** [comment] 2020-07-16 18:13
hi @jxnu-liguobin 
I think the issue is in the following part:
```java
Config.httpEntity(graphQLRequest)
```
Are you using a `.toString()`? There's a method to properly serialize a GraphQL request: 
**`graphQLRequest.toHttpJsonBody()`**
Please try this and let me know how it works.

**Comment by jxnu-liguobin** [comment] 2020-07-17 02:02
thanks, i have did it, 
```
    public static HttpEntity<String> httpEntity(GraphQLRequest request) {
        HttpHeaders headers = new HttpHeaders();
        headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
        headers.setContentType(MediaType.APPLICATION_JSON);
        return new HttpEntity<>(request.toHttpJsonBody(), headers);
    }

```
so request is successfully, but response error when deserializer

**Comment by kobylynskyi** [comment] 2020-07-17 02:11
Can you please try setting the property `modelNameSuffix`? 
Just to understand whether the problem is (is not) related to the conflict between class `io.github.dreamylost.model.Character` and [java.lang.Character](https://docs.oracle.com/javase/8/docs/api/java/lang/Character.html).
Thanks!

**Comment by jxnu-liguobin** [comment] 2020-07-17 02:20
setting
![image](https://user-images.githubusercontent.com/29496873/87741303-bfbea700-c816-11ea-91e3-08902396fad0.png)
java code
![image](https://user-images.githubusercontent.com/29496873/87741317-cb11d280-c816-11ea-8c14-0093479c0654.png)
exception
![image](https://user-images.githubusercontent.com/29496873/87741336-da911b80-c816-11ea-8b97-4e2955c90e6a.png)

Although there is no solution,But I think absolute path is a good choice, like protobuf

**Comment by jxnu-liguobin** [comment] 2020-07-17 02:23
It may have something to do with Jackson configuration, because I used the default configuration, but the interface has multiple subclasses？i am not sure

**Comment by kobylynskyi** [comment] 2020-07-17 02:23
Oh, so Character is interface. I didn't notice from your initial request.
In this case, you need to add `__typename` to the response projection (using `typename()`) and create your own serializer which will do the job based on the type of Character (Droid/Human/etc).

**Comment by jxnu-liguobin** [comment] 2020-07-17 02:31
but i can not find typename() in CharacterResponseProjection, need some setting?

**Comment by kobylynskyi** [comment] 2020-07-17 02:40
Oh, you are right! 
So there are two issues:
1. `typename()` is added only to unions as of now. It should be possible to specify it for interfaces too.
2. Another issue is that `customAnnotationsMapping` is only supported for field-level and not class-level.

I will implement both of these issues on Friday/Saturday and you should get the build over the weekend.
Plus I will document the approach of writing the serializer.

Thanks again for finding this!

**Comment by jxnu-liguobin** [comment] 2020-07-17 02:46
Oh, add typename  is very nice，but  i think we need `customAnnotationsMapping` for class-level to impl pagination. beacuse we have did it at my company

**Comment by kobylynskyi** [comment] 2020-07-17 02:49
Yes, that's exactly what we need to do.

So that your generated class will be:
```java
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = io.github.dreamylost.jackson.CharacterDeserializer.class)
public interface Character {
```
in case you specified it in your config):
```sbt
customAnnotationsMapping := {
  val mapping = new util.HashMap[String, String]
  mapping.put("Character", "com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = io.github.dreamylost.jackson.CharacterDeserializer.class)")
  mapping
}
```

**Comment by jxnu-liguobin** [comment] 2020-07-17 02:56
Let me summarize this question
1. `customAnnotationsMapping` at class-level
2. typename in interface
3. named conflict with java.lang.*

Besides, I would like to ask,can you see the plug-in I implemented? I wonder if I can submit a PR for scala platform(It may not be perfect now, but if can, i will do it continue)

**Comment by kobylynskyi** [comment] 2020-07-17 03:06
Created separate issues to track it: #230 and #231
And I don't see any issues with conflicting names:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/2664706/87744238-90754f00-c7b0-11ea-9416-881377bada1c.png">

**Comment by jxnu-liguobin** [comment] 2020-07-17 03:09
![image](https://user-images.githubusercontent.com/29496873/87744376-f5b35980-c81d-11ea-93f5-1abdf94f087f.png)
It may be because the scala standard library is imported automatically java.lang

**Comment by kobylynskyi** [comment] 2020-07-17 03:12
Yeah, agree. Maybe scala is doing some background work.
So I would suggest to specify a custom type mapping:
```groovy
customTypesMapping = [
    Character: "io.github.dreamylost.model.Character"
]
```

**Comment by jxnu-liguobin** [comment] 2020-07-17 03:17
Oh，thanks

**Comment by kobylynskyi** [comment] 2020-07-17 03:18
So can I close this issue?
We will track the other two requests separately.

**Comment by jxnu-liguobin** [comment] 2020-07-17 03:18
yes

**Closed** 2020-07-17 03:19 UTC
Labels: bug

**Comment by jxnu-liguobin** [comment] 2020-07-20 07:34
how can i distinguish between multiple types, such as
```
interface Character {
    id: ID!
    name: String!
    friends: [Character]
    appearsIn: [Episode]!
    secretBackstory : String @deprecated(reason : "We have decided that this is not canon")
}

type Human implements Character {
    id: ID!
    name: String!
    friends: [Character]
    appearsIn: [Episode]!
    homePlanet: String
}

type Droid implements Character {
    id: ID!
    name: String!
    friends: [Character]
    appearsIn: [Episode]!
}
```
Because the only different field is optional,

**Comment by jxnu-liguobin** [comment] 2020-07-20 12:48
if i use two jackson annotations like this
![image](https://user-images.githubusercontent.com/29496873/87936941-58c71980-cac6-11ea-98f7-b76924d52464.png)

It doesn't generate annotations on the interface，i don't want to write a decoder for every generic,  this will not make good use of typename, and it is not convenient for highly abstract domain models.
also i can not put two equals key to map

another question is if annotation's value has `"`, will create code error like this:
```
  mapping.put("User","com.fasterxml.jackson.annotation.JsonSubTypes(use=com.fasterxml.jackson.annotation.JsonTypeInfo.Id.NAME, include=com.fasterxml.jackson.annotation.JsonTypeInfo.As.PROPERTY,property = \"__typename\" ")
```

Even if I added an escape
![image](https://user-images.githubusercontent.com/29496873/87939081-143d7d00-caca-11ea-95ca-74606ff76f87.png)

My idea is that HashMap [string, string] may not be enough，Or run to convert the full annotation to a string and replace it directly

**Comment by kobylynskyi** [comment] 2020-07-20 13:00
Please take a look at the example-client project for Maven and Gradle.

And I am open to any suggestions how this can be improved.

**Comment by jxnu-liguobin** [comment] 2020-07-21 01:58
Oh, i see this option  customAnnotationsMapping' key is not contains modelNameSuffix 
![image](https://user-images.githubusercontent.com/29496873/88004025-c2800b80-cb38-11ea-935c-4e957b00bb81.png)

**Comment by kobylynskyi** [comment] 2020-07-21 02:00
Correct

**Comment by kobylynskyi** [comment] 2020-07-21 02:14
The leading `@` in `customAnnotationsMapping` can be added too for consistency purposes, **but in the future release** (done in #239 )
