### ISSUE TITLE
plugins support get schema files from URL

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#266] opened 2020-08-05 07:29 UTC
**Is your feature request related to a problem? Please describe.**
plugins support get schema files from URL/FTP. (one contains all graphql schemas)

**Describe the solution you'd like**
Code generation depends on the schema file. Although getting from URL may cause the client to be forced to update by the server schema, but even if it does not, the client will not get the correct response when calling the server. If the server schema changes, the graphql' api must have changed. So should we manage schema uniformly?

Of course, I'm not sure if using URLs will cause frequent updates on the client side.
Now, we can use copy to make both sides consistent

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment] 2020-08-05 17:42
@jxnu-liguobin I think it is duplicate of #165

**Closed** 2020-08-12 18:51 UTC
