### ISSUE TITLE
[unable to generate code for .graphqls file having "extend type Query"] (Version: [graphql-java-codegen version])

### ISSUE THREAD

**Issue by MeghnaChhabria** [kobylynskyi/graphql-java-codegen#80] opened 2020-04-20 11:16 UTC
## Issue Description

*I have multiple graphqls files which I am defining in <graphqlSchemaPath>, some of my files have an "extend type Query" which is leading to the following error:
java.nio.file.FileAlreadyExistsException: File already exists: /Users/meghnaashokchhabria/IdeaProjects/api/src/main/java/harness/graphql/client/model/Query.java*

I'm using the maven plugin

**Comment by joffrey-bion** [comment] 2020-04-20 11:25
Hi, and thanks for reporting this issue. Extensions might not be supported yet in this library, hence the issues you are facing. I'll let the maintainer of the library @kobylynskyi confirm this.

If it is the case, we should consider adding support for that as more and more people are using federation.

**Comment by joffrey-bion** [comment] 2020-04-20 11:42
After verification, it does seem that extensions are not really supported:
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/src/main/java/com/kobylynskyi/graphql/codegen/model/DefinitionTypeDeterminer.java#L10

In fact, this doesn't fail because `ObjectTypeExtensionDefinition` extends `ObjectTypeDefinition`. But the extensions are effectively considered as independent types with the same name as the original type, which is why it fails.

I created a feature request here https://github.com/kobylynskyi/graphql-java-codegen/issues/81, making this issue a duplicate of it.

**Closed by joffrey-bion** 2020-04-20 11:42 UTC
Labels: bug
