### ISSUE TITLE
provide Lombok compatibility

### ISSUE THREAD

**Issue by FyiurAmron** [kobylynskyi/graphql-java-codegen#1390] opened 2023-11-13 09:47 UTC
**Is your feature request related to a problem? Please describe.**
Providing Lombok annotations on-demand in autogenerated code instead of e.g. hardcoded getters/setters/builders would allow to easily customize the generation using its config options or annotation modifiers.

**Describe the solution you'd like**
Easy way to plug Lombok into the generated code.

**Describe alternatives you've considered**
Hacking the annotations into generated code via `generatedAnnotation` and disabling autogeneration via `generateModelsWithPublicFields` set to true - it fails on booleans, but that can be fixed via `lombok.getter.noIsPrefix = true` (which sadly needs to be enabled/disabled per directory, which requires additional copying of the file to generated dir) - but since `generatedAnnotation` applies to all generated files and not only to resolver/type classes, this ultimately fails.

**Comment by kobylynskyi** [comment] 2024-02-24 16:14
Lombok annotations do not work for generated sources.
Closing as a duplicate of #146

**Closed by kobylynskyi** 2024-02-24 16:14 UTC
